package.path = "./src/?.lua;./src/?/init.lua;./tests/?.lua;./tests/?/init.lua;./?.lua;./?/init.lua;" .. package.path

require("tests/test_json")
require("tests/test_inbox")
require("tests/test_chaos")
require("tests/room/test_sessions")
require("tests/room/test_encounters")
require("tests/keepsakes/test_encounter_effects")
require("tests/keepsakes/test_aromatic_phial")
require("tests/keepsakes/test_conformance")
require("tests/test_protocol")
require("tests/test_runtime_session")
require("tests/structure/test_room_and_navigation")
require("tests/structure/test_f_g_matrix")
require("tests/test_native_adapters")
require("tests/room/test_ordinary_traits")
require("tests/keepsakes/test_concave_stone")
require("tests/room/test_chaos_traits")
require("tests/room/test_level_acquisitions")
require("tests/room/test_direct_pickup_acquisitions")
require("tests/room/test_sea_star")
require("tests/room/test_npc_acquisitions")
require("tests/room/test_mystery_acquisitions")
require("tests/room/test_spell_acquisitions")
require("tests/room/test_path_acquisitions")
require("tests/room/test_transformations")
require("tests/room/test_nemesis_encounters")
require("tests/test_loadout_v11")
require("tests/test_hook_composition")

local lu = require("luaunit")
os.exit(lu.LuaUnit.run())
